services:
  api:
    image: stephenafamo/adonisjs
    container_name: api
    ports: 
      - 5000:80
    volumes:
      - ./API:/var/www
  app:
    image: node:lts
    container_name: app
    working_dir: /src
    command: yarn dev
    ports:
      - 4000:3000
    volumes:
      - ./App:/src
    environment:
      HOST: 0.0.0.0
  # database:
      
  